import type { Metadata } from "next";
import { GFS_Didot } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/landing/navber";
import { Footer } from "@/components/landing/footer";

const gfsDidot = GFS_Didot({
  variable: "--font-sans",
  subsets: ["greek"], // Note: GFS Didot is primarily Greek, but supports latin too. Next.js might require latin subset or no subsets if not available.
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "CodeGrid",
  description: "Generated by CodeGrid",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${gfsDidot.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white dark:bg-black">
        <Navbar />
        <main className="flex-1 flex flex-col">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
